### ISSUE TITLE
Testing: Add Cypress to Todo App

### ISSUE THREAD

**Issue by codingbootcampseu** [glissario/bootcamp-schedule#87]
Use Cypress to add e2e tests to your todo app and cover all important features with tests.

- [x] Add new todo
- [x] Filter todos
- [x] Remove done todos
- [x] Only allow todos with at least 5 characters

**Comment by glissario** [comment]
three tests are running (including github)

**Comment by glissario** [comment]
integrated fourth test
